# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'BusSchedules' do
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Google-Mobile-Ads-SDK'
    pod 'SBNag.swift'
end
